os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/master/Scripts/Travis/install.sh)"
script:
  - swift build
  - swift build -c release
  - swift test
after_success:
  - swift package generate-xcodeproj
  - xcodebuild -project MuttonChop.xcodeproj -scheme MuttonChop -sdk macosx10.12 -destination arch=x86_64 -configuration Debug -enableCodeCoverage YES test | xcpretty
  - bash <(curl -s https://codecov.io/bash)
